
import React, { useState, useMemo } from 'react';
import { Download, Mail, Trash2, FileText, ChevronDown, ChevronUp, User, Package, Clock, BarChart3, ClipboardCheck, Printer, CalendarDays, Filter, Truck, Ambulance, Table, AlertTriangle, AlertCircle, Trash, Timer, CheckCircle, Lock, ArrowUpDown } from 'lucide-react';
import { Withdrawal, Role, Medicine, InventoryAudit, Delivery, AppSettings, User as UserType, ExpiredMedicineLog, DeletionLog } from '../types';

interface ReportsProps {
  t: any;
  withdrawals: Withdrawal[];
  setWithdrawals: React.Dispatch<React.SetStateAction<Withdrawal[]>>;
  deliveries: Delivery[];
  disposals: ExpiredMedicineLog[];
  deletionLogs: DeletionLog[];
  role: Role;
  medicines: Medicine[];
  audits?: InventoryAudit[];
  settings: AppSettings;
  currentUser: UserType;
}

const Reports: React.FC<ReportsProps> = ({ t, withdrawals, deliveries, disposals, deletionLogs, medicines, settings, currentUser }) => {
  const [reportTab, setReportTab] = useState<'withdrawals' | 'entries' | 'disposals' | 'expiry' | 'deletions'>('withdrawals');
  const [timeFilter, setTimeFilter] = useState<'all' | 'daily' | 'weekly' | 'monthly' | 'yearly'>('all');
  const [sortBy, setSortBy] = useState<'medicine' | 'member'>('medicine');
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const filterByTime = (dateStr: string) => {
    if (timeFilter === 'all') return true;
    const date = new Date(dateStr);
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const days = diff / (1000 * 3600 * 24);
    if (timeFilter === 'daily') return days <= 1;
    if (timeFilter === 'weekly') return days <= 7;
    if (timeFilter === 'monthly') return days <= 30;
    if (timeFilter === 'yearly') return days <= 365;
    return true;
  };

  const filteredWithdrawals = useMemo(() => {
    return withdrawals
      .filter(w => filterByTime(w.timestamp))
      .sort((a, b) => {
        if (sortBy === 'medicine') return a.medicineName.localeCompare(b.medicineName);
        return a.username.localeCompare(b.username);
      });
  }, [withdrawals, timeFilter, sortBy]);

  const filteredDeliveries = useMemo(() => deliveries.filter(d => filterByTime(d.timestamp)), [deliveries, timeFilter]);
  const filteredDisposals = useMemo(() => disposals.filter(d => filterByTime(d.disposedAt)), [disposals, timeFilter]);
  const filteredDeletions = useMemo(() => deletionLogs.filter(d => filterByTime(d.timestamp)), [deletionLogs, timeFilter]);

  const expiringMeds = medicines.filter(m => {
    const exp = new Date(m.expiryDate);
    const now = new Date();
    return exp <= new Date(now.getTime() + (30 * 24 * 60 * 60 * 1000)) && exp >= now;
  });

  // Export Functions
  const exportToExcel = () => {
    let csvContent = "data:text/csv;charset=utf-8,";
    csvContent += "Medicine,Quantity,Date,Member,Vehicle,Signature\n";
    filteredWithdrawals.forEach(w => {
      csvContent += `"${w.medicineName}",${w.quantity},"${new Date(w.timestamp).toLocaleString()}","${w.username}","${w.vehicle}","${w.signature}"\n`;
    });
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `Tactical_Withdrawals_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const exportToPDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    const content = filteredWithdrawals.map(w => `
      <tr>
        <td>${w.medicineName}</td>
        <td>${w.quantity}</td>
        <td>${new Date(w.timestamp).toLocaleString()}</td>
        <td>${w.username}</td>
        <td>${w.vehicle}</td>
        <td style="font-family: monospace; font-size: 8px;">${w.signature}</td>
      </tr>
    `).join('');

    printWindow.document.write(`
      <html>
        <head>
          <title>Tactical Report - ${settings.appName}</title>
          <style>
            body { font-family: sans-serif; padding: 30px; color: #0a1628; }
            h1 { color: #0a1628; border-bottom: 3px solid #ffd700; padding-bottom: 10px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #e2e8f0; padding: 12px; text-align: left; font-size: 10px; }
            th { background-color: #f8fafc; font-weight: bold; text-transform: uppercase; }
          </style>
        </head>
        <body>
          <h1>Stock Withdrawal Audit</h1>
          <p>Generated by: ${currentUser.username} | ${new Date().toLocaleString()}</p>
          <table>
            <thead>
              <tr>
                <th>Medicine</th><th>Qty</th><th>Date</th><th>Member</th><th>Unit</th><th>Signature</th>
              </tr>
            </thead>
            <tbody>${content}</tbody>
          </table>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="space-y-6 md:space-y-10 animate-in fade-in duration-500 pb-20 px-1">
      <header className="flex flex-col md:flex-row justify-between items-center gap-4">
        <div>
          <h1 className="text-3xl font-black uppercase text-white tracking-tight">{t.reports}</h1>
          <p className="text-[10px] text-slate-500 uppercase font-bold tracking-widest">{t.generatedBy}: {currentUser.username}</p>
        </div>
        <div className="flex bg-[#0d1b2e] p-1.5 rounded-2xl border border-white/5 shadow-xl w-full md:w-auto overflow-x-auto no-scrollbar">
           <TabBtn active={reportTab === 'withdrawals'} onClick={() => setReportTab('withdrawals')} label={t.stockOut} />
           <TabBtn active={reportTab === 'entries'} onClick={() => setReportTab('entries')} label={t.stockIn} />
           <TabBtn active={reportTab === 'expiry'} onClick={() => setReportTab('expiry')} label="Expiry Watch" />
           <TabBtn active={reportTab === 'disposals'} onClick={() => setReportTab('disposals')} label={t.disposalReport} />
           <TabBtn active={reportTab === 'deletions'} onClick={() => setReportTab('deletions')} label={t.deletionHistory} />
        </div>
      </header>

      <div className="bg-[#0d1b2e] p-6 rounded-[32px] border border-white/5 space-y-6">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-4 bg-[#0a1628] px-5 py-3 rounded-2xl">
             <Filter size={18} className="text-accent" />
             <span className="text-[10px] font-black uppercase text-slate-500">Mission Duration:</span>
             <select value={timeFilter} onChange={e=>setTimeFilter(e.target.value as any)} className="bg-transparent border-none text-accent font-black uppercase text-[10px] outline-none cursor-pointer">
                <option value="all">{t.allTime}</option>
                <option value="daily">{t.daily}</option>
                <option value="weekly">{t.weekly}</option>
                <option value="monthly">{t.monthly}</option>
                <option value="yearly">{t.yearly}</option>
             </select>
          </div>

          {reportTab === 'withdrawals' && (
             <div className="flex items-center gap-2">
                <div className="flex bg-[#0a1628] p-1 rounded-xl border border-white/5">
                   <button onClick={() => setSortBy('medicine')} className={`px-3 py-1.5 rounded-lg text-[8px] font-black uppercase transition-all ${sortBy === 'medicine' ? 'bg-accent text-[#0a1628]' : 'text-slate-500'}`}>By Medicine</button>
                   <button onClick={() => setSortBy('member')} className={`px-3 py-1.5 rounded-lg text-[8px] font-black uppercase transition-all ${sortBy === 'member' ? 'bg-accent text-[#0a1628]' : 'text-slate-500'}`}>By Member</button>
                </div>
                <button onClick={exportToPDF} className="p-3 bg-white/5 text-slate-400 rounded-xl hover:text-white transition-all"><Printer size={18}/></button>
                <button onClick={exportToExcel} className="p-3 bg-white/5 text-emerald-500 rounded-xl hover:bg-emerald-500/10 transition-all"><Table size={18}/></button>
             </div>
          )}
        </div>

        <div className="space-y-3">
          {reportTab === 'withdrawals' && filteredWithdrawals.map(w => (
            <ReportItem key={w.id} icon={<Package size={16}/>} title={w.medicineName} subtitle={w.username} qty={`-${w.quantity}`} date={new Date(w.timestamp).toLocaleString()} expanded={expandedId === w.id} onToggle={() => setExpandedId(expandedId === w.id ? null : w.id)}>
               <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  <DetailItem label="Operational Unit" value={w.vehicle} />
                  <DetailItem label="Validated By" value={w.username} />
                  <DetailItem label="Auth Signature" value={w.signature} />
                  {w.incidentNumber && <DetailItem label="Incident #" value={w.incidentNumber} />}
               </div>
            </ReportItem>
          ))}
          {reportTab === 'entries' && filteredDeliveries.map(d => (
            <ReportItem key={d.id} icon={<Truck size={16}/>} title={d.medicineName} subtitle={d.username} qty={`+${d.quantity}`} date={new Date(d.timestamp).toLocaleString()} expanded={expandedId === d.id} onToggle={() => setExpandedId(expandedId === d.id ? null : d.id)}>
               <div className="grid grid-cols-2 gap-4"><DetailItem label="Operator" value={d.username} /><DetailItem label="Datum" value={new Date(d.timestamp).toLocaleDateString()} /></div>
            </ReportItem>
          ))}
          {reportTab === 'disposals' && filteredDisposals.map(d => (
            <ReportItem key={d.id} icon={<Trash2 size={16}/>} title={d.medicineName} subtitle={d.disposedBy} qty={`-${d.quantity}`} date={new Date(d.disposedAt).toLocaleString()} expanded={expandedId === d.id} onToggle={() => setExpandedId(expandedId === d.id ? null : d.id)}>
               <div className="grid grid-cols-2 gap-4"><DetailItem label="Grund" value="Abgelaufen" /><DetailItem label="Barcode" value={d.barcode} /></div>
            </ReportItem>
          ))}
          {reportTab === 'deletions' && filteredDeletions.map(d => (
            <ReportItem key={d.id} icon={<Trash size={16}/>} title={d.medicineName} subtitle={d.deletedBy} qty={`-${d.quantity}`} date={new Date(d.timestamp).toLocaleString()} expanded={expandedId === d.id} onToggle={() => setExpandedId(expandedId === d.id ? null : d.id)}>
               <div className="grid grid-cols-2 gap-4"><DetailItem label="Autorisiert von" value={d.deletedBy} /></div>
            </ReportItem>
          ))}
          {reportTab === 'expiry' && expiringMeds.map(m => (
            <div key={m.id} className="bg-[#0a1628] p-5 rounded-2xl border border-red-500/20 flex justify-between items-center shadow-lg">
               <div><h3 className="text-white font-black uppercase text-sm">{m.name}</h3><p className="text-red-500 font-bold text-[8px] uppercase tracking-widest">Ablauf: {m.expiryDate}</p></div>
               <div className="text-right text-red-500 font-black text-xl">{m.currentStock}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

const TabBtn = ({ active, onClick, label }: any) => (
  <button onClick={onClick} className={`px-4 py-2.5 rounded-xl text-[9px] font-black uppercase transition-all whitespace-nowrap ${active ? 'bg-accent text-[#0a1628] shadow-accent' : 'text-slate-500 hover:text-white'}`}>{label}</button>
);

const ReportItem = ({ icon, title, subtitle, qty, date, expanded, onToggle, children }: any) => (
  <div className="bg-[#0a1628] rounded-2xl border border-white/5 overflow-hidden transition-all shadow-lg hover:border-accent/20">
    <button onClick={onToggle} className="w-full p-5 flex items-center justify-between text-left">
      <div className="flex items-center gap-4"><div className="w-10 h-10 bg-[#0d1b2e] rounded-xl flex items-center justify-center text-accent">{icon}</div><div className="min-w-0"><h3 className="text-xs font-black text-white uppercase truncate max-w-[120px] md:max-w-none">{title}</h3><p className="text-[9px] text-slate-600 font-bold uppercase">{subtitle} • {date}</p></div></div>
      <div className="flex items-center gap-3"><span className={`px-3 py-1 rounded-lg text-[10px] font-black ${qty.startsWith('-') ? 'bg-red-500/10 text-red-500' : 'bg-emerald-500/10 text-emerald-500'}`}>{qty}</span>{expanded ? <ChevronUp size={16}/> : <ChevronDown size={16}/>}</div>
    </button>
    {expanded && <div className="p-6 bg-[#0d1b2e]/50 border-t border-white/5 animate-in slide-in-from-top-2">{children}</div>}
  </div>
);

const DetailItem = ({ label, value }: any) => (
  <div className="bg-[#0d1b2e] p-3 rounded-xl border border-white/5"><p className="text-[8px] font-black text-slate-600 uppercase tracking-widest mb-1">{label}</p><p className="text-xs font-black text-white break-all">{value}</p></div>
);

export default Reports;
